name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - BRANCH*

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
            POSTGRES_HOST_AUTH_METHOD: trust
        # Set health checks to wait until postgres has started
        options: >-
            --name postgres
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
        ports:
            - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodules
        shell: bash
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive --depth=1
      - uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: 17.0.9
          java-package: jdk+fx
          cache: 'gradle'
      - name: Build GanttProject
        run: ./gradlew --no-daemon build
      - name: Publish libs
        run: ./gradlew --no-daemon publishToMavenLocal
      - name: Initialize PostgreSQL
        run: |
          cd cloud.ganttproject.colloboque/src/main/resources
          docker run --rm --network ${{ job.container.network }} --link postgres:postgres -v $(pwd):/src -w /src postgres psql -h postgres -U postgres -f ./init-colloboque-server.sql
      - name: Build Colloboque
        run: cd cloud.ganttproject.colloboque && ./gradlew --no-daemon build
