name: Build Packages

on:
    push:
        branches: ['BRANCH*']
        paths: ['.github/workflows/test-codesign.yml']
env:
    MACOS_CERTIFICATE: ${{ secrets.PROD_MACOS_CERTIFICATE }}
    MACOS_CERTIFICATE_PWD: ${{ secrets.PROD_MACOS_CERTIFICATE_PWD }}
    MACOS_CERTIFICATE_NAME: ${{ secrets.PROD_MACOS_CERTIFICATE_NAME }}
    MACOS_CI_KEYCHAIN_PWD: ${{ secrets.PROD_MACOS_CI_KEYCHAIN_PWD }}

jobs:
    macOS_intel:
        runs-on: macos-13
        steps:
            - name: Test Code Sign
              run: |
                  echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
    
                  security create-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
                  security default-keychain -s build.keychain
                  security unlock-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
                  security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
                  security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MACOS_CI_KEYCHAIN_PWD" build.keychain
                  echo "Sign me" >> test
                  /usr/bin/codesign --force -s 10CA57E9AC0EF0A4328B7C1BA14B618E1208DEC1 test -v

